--
-- ER/Studio Data Architect SQL Code Generation
-- Project :      NYPD Arrest Data.DM1
--
-- Date Created : Thursday, February 13, 2025 22:00:00
-- Target DBMS : Snowflake
--

-- 
-- TABLE: DIM_BOROUGH 
--

CREATE TABLE DIM_BOROUGH(
    BOROUGH_ID     INTEGER       NOT NULL,
    ARREST_BORO    VARCHAR(5),
    CONSTRAINT PK_BOROUGH_ID PRIMARY KEY (BOROUGH_ID) 
)
;



-- 
-- TABLE: DIM_DATE 
--

CREATE TABLE DIM_DATE(
    DATE_KEY        INTEGER         NOT NULL,
    FULL_DATE       DATE,
    DAY_OF_WEEK     VARCHAR(15),
    WEEK_OF_YEAR    INTEGER,
    MONTH           INTEGER,
    QUARTER         INTEGER,
    YEAR            INTEGER,
    WEEKEND         NUMBER(2, 0),
    DI_JOB_ID       VARCHAR(100),
    DI_LOAD_DT      DATE,
    CONSTRAINT PK8 PRIMARY KEY (DATE_KEY) 
)
;



-- 
-- TABLE: DIM_LAW 
--

CREATE TABLE DIM_LAW(
    LAW_ID        VARCHAR(20)    NOT NULL,
    LAW_CODE      VARCHAR(20),
    LAW_CAT_CD    VARCHAR(5),
    CONSTRAINT PK_LAW_ID PRIMARY KEY (LAW_ID) 
)
;



-- 
-- TABLE: DIM_LOCATION 
--

CREATE TABLE DIM_LOCATION(
    LOCATION_ID    INTEGER    NOT NULL,
    X_COORD_CD     FLOAT,
    Y_COORD_CD     FLOAT,
    LATITUDE       FLOAT,
    LONGITUDE      FLOAT,
    CONSTRAINT PK_LOCATION_ID PRIMARY KEY (LOCATION_ID) 
)
;



-- 
-- TABLE: DIM_OFFENSE 
--

CREATE TABLE DIM_OFFENSE(
    OFFENSE_ID    INTEGER         NOT NULL,
    PD_CD         INTEGER,
    PD_DESC       VARCHAR(255),
    KY_CD         INTEGER,
    OFNS_DESC     VARCHAR(255),
    CONSTRAINT PK_OFFENSE_ID PRIMARY KEY (OFFENSE_ID) 
)
;



-- 
-- TABLE: DIM_PERPETRATOR 
--

CREATE TABLE DIM_PERPETRATOR(
    PERP_ID      INTEGER        NOT NULL,
    AGE_GROUP    VARCHAR(20),
    PERP_SEX     VARCHAR(1),
    PERP_RACE    VARCHAR(50),
    CONSTRAINT PK_PERP_ID PRIMARY KEY (PERP_ID) 
)
;



-- 
-- TABLE: DIM_PRECINCT 
--

CREATE TABLE DIM_PRECINCT(
    PRECINCT_ID        INTEGER    NOT NULL,
    ARREST_PRECINCT    INTEGER,
    CONSTRAINT PK_PRECINCT_ID PRIMARY KEY (PRECINCT_ID) 
)
;



-- 
-- TABLE: FACT_ARREST 
--

CREATE TABLE FACT_ARREST(
    ARREST_KEY           INTEGER        NOT NULL,
    PRECINCT_ID          INTEGER        NOT NULL,
    LAW_ID               VARCHAR(20)    NOT NULL,
    BOROUGH_ID           INTEGER        NOT NULL,
    OFFENSE_ID           INTEGER        NOT NULL,
    LOCATION_ID          INTEGER        NOT NULL,
    PERP_ID              INTEGER        NOT NULL,
    DATE_KEY             INTEGER        NOT NULL,
    ARREST_DATE          DATE,
    JURISDICTION_CODE    INTEGER,
    CONSTRAINT PK_ARREST_KEY PRIMARY KEY (ARREST_KEY, PRECINCT_ID, LAW_ID, BOROUGH_ID, OFFENSE_ID, LOCATION_ID, PERP_ID, DATE_KEY) 
)
;



-- 
-- TABLE: FACT_ARREST 
--

ALTER TABLE FACT_ARREST ADD CONSTRAINT RefDIM_PRECINCT1 
    FOREIGN KEY (PRECINCT_ID)
    REFERENCES DIM_PRECINCT(PRECINCT_ID)
;

ALTER TABLE FACT_ARREST ADD CONSTRAINT RefDIM_LAW2 
    FOREIGN KEY (LAW_ID)
    REFERENCES DIM_LAW(LAW_ID)
;

ALTER TABLE FACT_ARREST ADD CONSTRAINT RefDIM_BOROUGH3 
    FOREIGN KEY (BOROUGH_ID)
    REFERENCES DIM_BOROUGH(BOROUGH_ID)
;

ALTER TABLE FACT_ARREST ADD CONSTRAINT RefDIM_OFFENSE4 
    FOREIGN KEY (OFFENSE_ID)
    REFERENCES DIM_OFFENSE(OFFENSE_ID)
;

ALTER TABLE FACT_ARREST ADD CONSTRAINT RefDIM_LOCATION5 
    FOREIGN KEY (LOCATION_ID)
    REFERENCES DIM_LOCATION(LOCATION_ID)
;

ALTER TABLE FACT_ARREST ADD CONSTRAINT RefDIM_PERPETRATOR6 
    FOREIGN KEY (PERP_ID)
    REFERENCES DIM_PERPETRATOR(PERP_ID)
;

ALTER TABLE FACT_ARREST ADD CONSTRAINT RefDIM_DATE7 
    FOREIGN KEY (DATE_KEY)
    REFERENCES DIM_DATE(DATE_KEY)
;


